resolver: lts-6.0
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

require-stack-version: ">= 0.1.8"

packages:
- location: .

- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: a06d50dedf9a705f9327bbe0a15c8131ad80b2f9
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: a2b76b1892549f1b6834b3d81bd9bec963aa2a6f
  extra-dep: true

- location: ../../servant-reflex
  extra-dep: true

- location: ../lib
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.3.1
- ref-tf-0.4
- zenc-0.1.1
