resolver: lts-6.0
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

require-stack-version: ">= 0.1.8"

packages:
- location: .

- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 5b5a1c8d540ea9058988d4c564e2823aa099b840
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: e8b7d31fd2b6a8173e51096b7591ec346e33ad85
  extra-dep: true

- location:
    git: git@github.com:imalsogreg/servant-reflex.git
    commit: master
  extra-dep: true

- location: ../lib
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.3.1
- ref-tf-0.4
