resolver: lts-6.0
compiler: ghcjs-0.2.0.20160628_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160628_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160628_ghc-7.10.3.tar.gz

require-stack-version: ">= 0.1.8"

packages:
- location: .

- location: ../lib
  extra-dep: true

extra-deps:
- react-flux-1.2.1
