resolver: lts-7.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
          sha1: e640724883238593e2d2f7f03991cb413ec0347b

allow-newer: true
require-stack-version: ">= 0.1.8"

packages:
- location: .

- location: ../lib
  extra-dep: true

- location:
    hg: https://rubenmoor@bitbucket.org/rubenmoor/react-flux-servant
    commit: tip

extra-deps:
- react-flux-1.2.1
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsffi-0.3.1.0
