resolver: lts-6.15
compiler: ghcjs-0.2.0.9006015_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006015_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/lts-6.15-9006015.tar.gz"
         sha1: 4d513006622bf428a3c983ca927837e3d14ab687
allow-newer: true

require-stack-version: ">= 0.1.8"

packages:
- location: .

- location: ../lib
  extra-dep: true

extra-deps:
- react-flux-1.2.1
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsffi-0.3.1.0
