resolver: nightly-2016-09-04
compiler: ghcjs-0.2.0.820160904_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.820160904_ghc-8.0.1:
        url: "http://tolysz.org/ghcjs/ghc-8.0-2016-09-05-nightly-2016-09-04-820160904.tar.gz"
        sha1: "cf4383b77f9d712133bdf54e6389c4361c57b484"

allow-newer: true
require-stack-version: ">= 0.1.8"

packages:
- location: .

- location: ../lib
  extra-dep: true

extra-deps:
- react-flux-1.2.1
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsffi-0.3.1.0
