resolver: lts-8.0
packages:
  - '.'
  - '../lib'
  - '../../../purescript-bridge'

extra-deps:
  - servant-purescript-0.6.0.0
  - purescript-bridge-0.9.0.0
  # purescript-argonaut-generic-codecs does not yet support the breaking
  # aeson changes.
  - aeson-0.11.3.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
