resolver: lts-7.15
packages:
  - '.'
  - '../lib'
  - '../../../purescript-bridge'

extra-deps:
  - servant-purescript-0.6.0.0
  - purescript-bridge-0.9.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
