resolver: lts-9.0
packages:
  - '.'
  - '../lib'

extra-deps:
  - servant-purescript-0.8.0.0
  - purescript-bridge-0.10.1.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
