site_name: Herculus Docs
google_analytics: ["UA-85139321-2", "https://app.herculus.io/doc/"]
pages:
  - Home: index.md
  - Guides:
      - Building Your First App: guides/app.md
  - Formulas: formulas.md
theme: cinder
extra_css:
  - "css/herculus.css"
