site_name: Herculus Docs
nav:
  - Home: index.md
  - Guides:
      - Building Your First App: guides/app.md
  - Formulas: formulas.md
  - Function Reference: reference.md
theme: cinder
extra_css:
  - "css/herculus.css"
